### ISSUE TITLE
docs: Add resources regarding Good Practices

### ISSUE THREAD

**Issue by tbobm** [open-subjects/open-subjects#22]
Add links or describe methodology concepts:
- [x] Commits (conventional commits)
- [x] Issues
- [x] Documentation (setting up, autogenerate documentation, maintain)
- [ ] SOLID principles (TBD)
- [x] [Hexagonal Architecture](https://blog.octo.com/architecture-hexagonale-trois-principes-et-un-exemple-dimplementation/)
- [x] Linting
- [ ] Project packaging

**Comment by TristanMarion** [comment]
- Conventional commits
- SOLID principles
- Hexagonal architecture

**Comment by valentinmne** [comment]
- Create and maintain a good documentation all along the project
- Setup a project the right way (Python, C,Docker...)
- Tools for good practices (linter...)

**Comment by tbobm** [comment]
Thank you guys, I have edited the issue. I think it'll probably become a "label:meta" issue soon, as most of these subjects can require some time to be crunched and packaged.

I think the `Commits`/`Issues`/`Linting` might be the easiest ones to cover in the short term and the most rewarding towards people looking for easily applicable knowledge in a lot of contexts.

Feel free to complete with additional links to resources to allow handling these subjects using the "short description + link to full resource" method (a good ol' TLDR with a couple of examples would ease getting a grasps at the Good Practices)

**Comment by tbobm** [comment]
@TristanMarion do you have any recommended links regarding SOLID principles ? Books ?
